on: [push]

jobs:
        ci:
                runs-on: ubuntu-latest
                name: test
                steps:
                        - name: run the test
                          run: |
                              echo "this is test"


